### ISSUE TITLE
Does it work for react-native

### ISSUE THREAD

**Issue by muhammadwafa** [acornjs/acorn-jsx#111]
I am strongly need a package to convert `String` into `JSX`, is this package works for `react-native` too?

**Comment by cawfree** [comment]
[react-jsx-parser](https://www.npmjs.com/package/react-jsx-parser) works on RN. You just need to set the `renderInWrapper` prop to `false`.

**Comment by muhammadwafa** [comment]
sorry does not work for me with or without `renderInWrapper={false}`

**Comment by cawfree** [comment]
Maybe it's the version I was using.

How about if you use `"react-jsx-parser": "1.16.1"`?

**Comment by muhammadwafa** [comment]
I am using `latest` version, and this is the string I am going to parse it.

`const strJSX = "<Text onPress={()=> alert('Hi I am parsed')} style={{color: 'red', lineHeight: '40', borderRadius: 20, margin: 5, padding: 5, fontWeight: 'bold'}}>Hi dear this is a jsx string</Text>";`


Could you please test the above string and parse it to `react-native` jsx?

**Comment by RReverser** [comment]
Sorry, but this doesn't seem to be an issue. For questions and discussions, please use StackOverflow or https://discuss.ternjs.net/c/acorn.

**Comment by muhammadwafa** [comment]
@RReverser thank you
