### ISSUE TITLE
String Literals with newline not as expected

### ISSUE THREAD

**Issue by paranoidjk** [acornjs/acorn-jsx#119]
## Demo JSX Code
![image](https://user-images.githubusercontent.com/7971415/94571949-129aed00-02a3-11eb-8d81-1dcbe4c19065.png)

## AST Result
test in https://astexplorer.net/

![image](https://user-images.githubusercontent.com/7971415/94572004-20507280-02a3-11eb-886e-035910339f0c.png)

## Expect Result

according to https://reactjs.org/docs/jsx-in-depth.html
![image](https://user-images.githubusercontent.com/7971415/94572048-2a727100-02a3-11eb-993c-fe6545c8ae8b.png)

**Comment by RReverser** [comment]
This is a parser, not a React-specific transpiler. It intentionally returns the original text in case some other implementation of JSX wants to preserve those spaces.

**Comment by paranoidjk** [comment]
@RReverser Thanks for your quick answer, i try it in [babel repl,](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIogE6pQhlIA8AJjAG4B8AEhlogO5xnr0AhLQD0jVgG4iAXyJA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.11.6&externalPlugins=) loooks like it works fine

![image](https://user-images.githubusercontent.com/7971415/94634845-c338d900-0303-11eb-823b-7ab05361615c.png)


I just wonder if the acorn jsx parser don't do this,  who did this job?
